### ISSUE TITLE
Implement "Record Facts" Module

### ISSUE THREAD

**Issue by sbarbett** [ultradns/ultradns-ansible#10]
# Overview
Develop a new fact-gathering module named `record_facts` for UltraDNS. This module will retrieve a list of RRSet records for a specific zone by sending GET requests to the `/v3/zones/{zoneName}/rrsets` endpoint. The module should support a variety of query parameters for filtering (such as `ttl`, `owner`, and `value`), as well as parameters to control the kind of records returned (`kind`), sorting (`reverse`), and whether the records are system generated (`sys_generated`). Unlike the zone facts module, this endpoint uses offset-based pagination. The module must automatically follow pages until all records are gathered and then return them as Ansible facts.

# Requirements

1. **API Interaction:**
   - **GET Request Implementation:**
     - Send a GET request to `/v3/zones/{zoneName}/rrsets` where `{zoneName}` is provided by the user.
     - Always include a `limit=1000` parameter.
     - Use offset-based pagination:
       - Check the `resultInfo` section of the response for `totalCount`, `offset`, and `returnedCount`.
       - Automatically iterate through pages until all records are retrieved.
   - **Query Parameters (via the `q` parameter):**
     - **ttl:** Exact match for TTL (only valid for RECORDS RRSet type; ignore for others).
     - **owner:** Partial match for the owner name (applies to all RRSets).
     - **value:** Partial match for the rdata value (only valid for RECORDS RRSet type).
   - **Additional Query Options:**
     - **kind:** (defaults to ALL) Acceptable values: ALL, RECORDS, POOLS, RD_POOLS, DIR_POOLS, SB_POOLS, TC_POOLS.
     - **reverse:** If set to true, include the `reverse=true` parameter.
     - **sys_generated:** If set to true, include the `systemGeneratedStatus=true` parameter.

2. **Module Structure:**
   - **Separate Module:**
     - Create a new module file named `record_facts.py` under `plugins/modules/`.
   - **Shared API Function:**
     - Add a dedicated function in `plugins/module_utils/client.py` to handle the GET request and offset-based pagination.
     - Import and reuse this function within `record_facts.py`, following the pattern used by the other modules.

3. **Input Parameters:**
   - **Required:**
     - `zone`: The zone for which to retrieve records.
     - `provider`: Provider/connection details for UltraDNS.
   - **Optional:**
     - `owner`: To filter records by owner name.
     - `ttl`: To filter records by TTL (for RECORDS type only).
     - `value`: To filter records by rdata value (for RECORDS type only).
     - `kind`: To specify the type of RRSets (default is ALL).
     - `reverse`: To request descending order (boolean).
     - `sys_generated`: To filter for system-generated records (boolean).

4. **Return Data as Facts:**
   - **Output Structure:**
     - The module should collect all RRSet records from the `rrSets` field in the API response.
     - Return the data as an Ansible fact (for example, under the key `record_facts`):
       ```python
       module.exit_json(changed=False, ansible_facts={'record_facts': rrSets})
       ```
     - Set `changed` to `False` since this is a read-only operation.
   
5. **Error Handling & Documentation:**
   - **Error Handling:**
     - If the API returns an error (e.g., an error code indicating “Data not found”), handle it gracefully by returning an empty list or appropriate message without failing the play.
   - **Code Documentation:**
     - Include inline comments explaining:
       - How query parameters are constructed.
       - The process for offset-based pagination.
       - Error handling for cases when no data is found.
   - **Usage Example in Documentation:**
     ```yaml
     - name: Gather record facts
       ultradns.ultradns.record_facts:
         zone: example.com
         owner: test         # optional filter
         ttl: 300            # optional filter
         value: 1.1.         # optional filter
         kind: RECORDS       # optional filter
         reverse: true       # optional filter
         sys_generated: true # optional filter
         provider: "{{ ultra_provider }}"
       register: record_data

     - name: Display records
       ansible.builtin.debug:
         msg: "Found record: {{ item }}"
       loop: "{{ record_data.ansible_facts.record_facts }}"
     ```

# Acceptance Criteria
- The module sends a GET request to `/v3/zones/{zoneName}/rrsets` with the required `limit=1000` and any provided filters.
- It supports offset-based pagination by iterating through pages until all records are retrieved.
- All supported query parameters (`ttl`, `owner`, `value`, `kind`, `reverse`, `sys_generated`) are correctly applied to the request.
- A shared helper function in `plugins/module_utils/client.py` is implemented to handle the API request and pagination, and is reused in `record_facts.py`.
- The module returns the complete list of RRSet records as an Ansible fact under a key (e.g., `record_facts`), with `changed: False`.
- In cases where the API returns no data (or an error indicating data not found), the module handles it gracefully without failing the entire play.
- Comprehensive inline comments and documentation are provided, including a usage example.
