### ISSUE TITLE
Explicit RD Pool Support

### ISSUE THREAD

**Issue by sbarbett** [ultradns/ultradns-ansible#4]
# Summary

The collection needs a clearer approach to managing Resource Distribution (RD) Pools for A or AAAA records. When multiple addresses exist without `solo: true`, UltraDNS automatically creates a pool, but currently we cannot explicitly configure its properties (e.g., order, description). This new feature should allow operators to manage RD Pools with minimal friction and maximum control.

# Proposed YAML Manifest

Below is a draft example of how an Ansible task might look:

```yaml
- name: Create or Update an RD Pool
  ultradns.ultradns.rd_pool:
    zone: "andria.com"
    name: "redredrobin"
    type: "A"
    ttl: 86400
    data:
      - "198.16.1.22"
      - "192.168.2.56"
    order: "ROUND_ROBIN"            # or FIXED, RANDOM
    description: "T. migratorius"
    state: present

- name: Remove an RD Pool
  ultradns.ultradns.rd_pool:
    zone: "andria.com"
    name: "redredrobin"
    type: "A"
    state: absent
```

# Parameters (Proposed)

| Key           | Type    | Required | Default / Choices                | Description                                          |
|---------------|---------|----------|----------------------------------|------------------------------------------------------|
| `zone`        | string  | yes      | N/A                              | The DNS zone name in UltraDNS.                       |
| `name`        | string  | yes      | N/A                              | The record owner name within the zone.               |
| `type`        | string  | yes      | `A` or `AAAA`                    | Supported record type for RD Pools.                  |
| `ttl`         | integer | no       | 300                              | Time to live for the record set.                     |
| `data`        | list    | no       | []                               | IP addresses included in the RD Pool.                |
| `order`       | string  | no       | `FIXED`,`RANDOM`,`ROUND_ROBIN`   | The ordering strategy for the RD Pool.               |
| `description` | string  | no       | ""                               | Optional free-text description for the pool.         |
| `state`       | string  | no       | `present`                        | Whether the pool should exist or be removed.         |

# Acceptance Criteria

* The module allows explicit creation, update, and deletion of RD Pools.
* No change is made when the UltraDNS RD Pool matches the desired configuration.
* Multiple A/AAAA records can be managed under a single owner with control over order and optional description.
