### ISSUE TITLE
Implement "Get Zone Facts" Module

### ISSUE THREAD

**Issue by sbarbett** [ultradns/ultradns-ansible#8]
# Overview
This story involves developing a new fact-gathering module for UltraDNS that retrieves all DNS zones using a GET request to the `/v3/zones` endpoint. The module will support cursor-based pagination and a set of query parameters to filter results. The returned data—specifically the contents of the "zones" array—will be provided as Ansible facts for use in subsequent plays. This functionality is intended to clearly separate data retrieval from state-changing operations, following Ansible’s best practices.

# Requirements

1. **API Interaction:**
   - **GET Request Implementation:**
     - The module must send a GET request to the `/v3/zones` endpoint.
     - The request should always include a query parameter `limit=1000`.
   - **Cursor-Based Pagination:**
     - Use the `cursorInfo` in the API response to automatically follow pagination.
     - Continue making additional requests using the `cursor` parameter until no further pages exist.
   
2. **Module Structure:**
   - **Separate Fact Module:**
     - Create a new module file (e.g., `zone_facts.py`) within the modules directory, distinct from modules that perform state changes (like `zone.py`).
     - **Shared API Logic:**  
       - Add a function that retrieves zones (handling GET requests and pagination) to `plugins/module_utils/client.py`.
       - This new function should then be imported and used in `plugins/modules/zone_facts.py`, similar to how other modules leverage shared functionality.
   - **Return Data as Facts:**
     - Extract and return the data inside the "zones" array as an Ansible fact.
     - Format the output using the `ansible_facts` key, for example:
       ```python
       module.exit_json(changed=False, ansible_facts={'zones': zones})
       ```
     - Set `changed` to `False` to indicate that this operation does not alter any state.

3. **Query Parameter Support:**
   - **Filtering Capabilities:**
     - Allow the following optional parameters to be passed to the module:
       - `name`: For partial matching of the zone name.
       - `type`: Must be one of `PRIMARY`, `SECONDARY`, or `ALIAS` (case sensitive).
       - `status`: Should accept `ACTIVE`, `SUSPENDED`, or `ALL` (case sensitive); defaults to active zones if not provided.
       - `account`: Filters zones by account. Ensure any spaces in the account name are URL-encoded as `%20`.
       - `network`: Must accept `ultra1` or `ultra2` (defaults to `ultra1` if not specified).
   - **Example Query String:**
     - A request might look like:
       ```
       /v3/zones?name:example+zone_type:PRIMARY+network:ultra1&cursor=<cursor>&limit=1000
       ```

4. **Explanation & Comments:**
   - **Code Documentation:**
     - Add detailed comments in the module code to explain:
       - How the GET request is formed.
       - How query parameters are processed.
       - How pagination is handled using `cursorInfo`.
   - **Usage Documentation:**
     - Include a documentation block within the module that provides an example similar to:
       ```yaml
       - name: Gather zone facts
         ultradns.ultradns.zone_facts:
           name: example        # optional filter
           type: PRIMARY        # optional filter
           status: ALL          # optional filter
           account: myaccount   # optional filter
           provider: "{{ ultra_provider }}"
         register: zone_data

       - name: Display zones
         ansible.builtin.debug:
           msg: "Found zone: {{ item.properties.name }}"
         loop: "{{ zone_data.ansible_facts.zones }}"
       ```

# Acceptance Criteria
- The new `zone_facts.py` module sends a GET request to `/v3/zones` with a `limit=1000` and applicable query parameters.
- The module automatically follows the cursor-based pagination until all pages have been fetched.
- Only the data inside the "zones" array is returned as an Ansible fact (e.g., under `ansible_facts.zones`).
- The module is idempotent and returns `changed: False`.
- Proper error handling is implemented—if the API returns an error, the module should fail gracefully using `module.fail_json()`.
- A new function for retrieving zones is added to `plugins/module_utils/client.py` and is reused in `plugins/modules/zone_facts.py`.
- The module includes comprehensive code comments and documentation within its usage examples.
