### ISSUE TITLE
Implement "Zone Meta Facts" Module

### ISSUE THREAD

**Issue by sbarbett** [ultradns/ultradns-ansible#9]
# Overview
This story covers the development of a new fact-gathering module called `zone_meta_facts` for UltraDNS. The module's purpose is to retrieve detailed metadata for a list of specific zones by sending GET requests to the `/v3/zones/{zone_name}` endpoint. Unlike the zone listing module, this endpoint does not support query parameters for filtering; it only returns metadata for the given zone. If a zone does not exist, the module should handle the error gracefully (for example, by skipping the zone or returning an empty result). The functionality and behavior should mirror that of our existing modules, ensuring consistency across the collection.

This is a continuation of https://github.com/ultradns/ultradns-ansible/issues/8

# Requirements

1. **API Interaction:**
   - **GET Request Implementation:**
     - For each zone specified in the input list, send a GET request to `/v3/zones/{zone_name}`.
     - Utilize a shared function for API interactions. Add this function to `plugins/module_utils/client.py` and then import and use it within the new module.
   - **Error Handling:**
     - If a request for a specific zone returns an error (e.g., the zone does not exist), the module should handle it gracefully, such as by logging a warning or returning a null/empty entry for that zone.
     - Ensure that the module does not fail the entire playbook unless there’s a systemic API failure.

2. **Module Structure:**
   - **Separate Module:**
     - Create a new module file, `zone_meta_facts.py`, under `plugins/modules/`.
     - This module should be separate from `zone_facts.py`, as it serves a distinct purpose (retrieving metadata for specific zones rather than listing zones with filtering).
   - **Shared API Function:**
     - Implement a dedicated function in `plugins/module_utils/client.py` to handle the GET request to `/v3/zones/{zone_name}`.
     - This function should encapsulate the HTTP call and error handling, and be reused by `zone_meta_facts.py`.

3. **Input Parameters:**
   - **Required Parameters:**
     - `provider`: The connection/provider details for UltraDNS.
     - `zones`: A list of zone names for which metadata should be retrieved.
   - **Optional Parameters:**
     - Consider supporting an option to continue processing other zones even if one fails (e.g., a `fail_on_error` flag).

4. **Return Data as Facts:**
   - **Output Structure:**
     - Return the metadata for each requested zone as Ansible facts.
     - Example output structure:
       ```python
       module.exit_json(changed=False, ansible_facts={'zone_meta': zone_metadata})
       ```
       where `zone_metadata` is a dictionary with keys as zone names and values as the respective metadata responses.
   - **Idempotence:**
     - Ensure that the module is idempotent by setting `changed` to `False`.

5. **Documentation & Comments:**
   - **Code Comments:**
     - Include detailed inline comments to explain the logic for iterating through the zone list, sending requests, handling pagination (if needed), and managing errors.
   - **Usage Example:**
     - Provide a clear usage example in the module documentation:
       ```yaml
       - name: Gather specific zones metadata
         ultradns.ultradns.zone_meta_facts:
           provider: "{{ ultra_provider }}"
           zones:
             - example1.com
             - example2.com
             - example3.com
         register: specific_zones

       - name: Display specific zone metadata
         ansible.builtin.debug:
           msg: "Metadata for zone {{ item.key }}: {{ item.value }}"
         loop: "{{ specific_zones.ansible_facts.zone_meta | dict2items }}"
       ```

# Acceptance Criteria
- The new `zone_meta_facts.py` module sends individual GET requests to `/v3/zones/{zone_name}` for each zone in the provided list.
- A shared helper function for these API requests is implemented in `plugins/module_utils/client.py` and is reused in `zone_meta_facts.py`.
- The module collects and returns metadata for each zone as an Ansible fact under `zone_meta` with the structure: `{ zone_name: <metadata>, ... }`.
- If a requested zone is not found, the module handles the error gracefully without failing the entire play, optionally logging a warning.
- The module is idempotent (returns `changed: False`).
- Comprehensive inline code comments and usage documentation are provided.
